import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

import { resolveInRepo } from './paths.mjs';
import { fragmentFingerprint } from './fragments.mjs';

export const REPO_CHANGELOG = 'CHANGELOG.md';

const GROUPS = [
  ['major', 'Breaking changes'],
  ['minor', 'Features'],
  ['patch', 'Fixes'],
];

// Anchored at both ends and at column zero, so only a line the renderer produced counts as
// evidence that a ref shipped. Fragment bodies are always indented and titles are single-line, so
// neither can forge one. The ref binds to the LAST parenthesised group, which is the one the
// renderer appends, so a title containing "(SQ-999)" cannot mark SQ-999 as released.
const RENDERED_ENTRY = /^- .* \(([A-Z][A-Z0-9]*-\d+)\)(?: \[`[0-9a-f]{7,40}`\]\([^\s)]*\))?$/;
const RENDERED_ENTRY_DETAILS = /^- (.*) \(([A-Z][A-Z0-9]*-\d+)\)(?: \[`([0-9a-f]{7,40})`\]\([^\s)]*\))?$/;

export function repoChangelogHeader() {
  return [
    '# Changelog',
    '',
    'One section per release window. Each window is a single commit on `main` that moves every',
    'changed plugin at once, tagged `v<marketplace version>`, with matching per-plugin changelogs',
    'under `plugins/<name>/CHANGELOG.md`.',
    '',
    'Releases before v3.208.0 predate this file and are not backfilled; `git log` is the record for',
    'those. Entries are generated from `.release/unreleased/*.md` by `scripts/release/cut.mjs`, so',
    'nothing here is hand-written.',
    '',
  ].join('\n');
}

export function pluginChangelogHeader(name) {
  return [
    `# ${name} changelog`,
    '',
    `Generated by \`scripts/release/cut.mjs\`. Versions before the first entry below are in \`git log\`.`,
    '',
  ].join('\n');
}

function commitLink(entry, repository) {
  if (!entry.commit) return '';
  const short = entry.commit.slice(0, 7);
  if (!repository) return ` \`${short}\``;
  return ` [\`${short}\`](${repository}/commit/${entry.commit})`;
}

function renderEntries(entries, repository, heading) {
  const lines = [];
  for (const [level, label] of GROUPS) {
    const matching = entries.filter((entry) => entry.level === level);
    if (matching.length === 0) continue;
    lines.push(`${heading} ${label}`, '');
    for (const entry of matching) {
      const bullet = `- ${entry.title} (${entry.ref})${commitLink(entry, repository)}`;
      const parsed = RENDERED_ENTRY.exec(bullet);
      if (parsed?.[1] !== entry.ref) {
        throw new Error(`the changelog line for ${entry.ref} does not read back as ${entry.ref}; refusing to write an entry the ledger cannot parse: ${bullet}`);
      }
      lines.push(bullet);
      const body = (entry.body ?? '').trim();
      // Two spaces on every body line keeps it out of column zero, where the ledger reads.
      if (body) {
        for (const line of body.split('\n')) lines.push(line.trim() === '' ? '' : `  ${line.trimEnd()}`);
      }
    }
    lines.push('');
  }
  return lines;
}

export function repoSectionHeading(plan) {
  return `## ${plan.tag} (${plan.date})`;
}

export function renderRepoSection(plan) {
  const lines = [repoSectionHeading(plan), ''];
  if (plan.mode === 'hotfix') {
    lines.push(`Hotfix release cut from \`${plan.publishBranch}\`.`, '');
  }
  for (const plugin of plan.plugins) {
    lines.push(`### ${plugin.name} ${plugin.from} → ${plugin.to}`, '');
    lines.push(...renderEntries(plugin.entries, plan.repository, '####'));
  }
  return `${lines.join('\n').trimEnd()}\n`;
}

export function pluginSectionHeading(plugin, plan) {
  return `## ${plugin.to} (${plan.date})`;
}

export function renderPluginSection(plugin, plan) {
  const lines = [pluginSectionHeading(plugin, plan), ''];
  lines.push(`Released in ${plan.tag}${plan.mode === 'hotfix' ? ' (hotfix)' : ''}, up from ${plugin.from}.`, '');
  lines.push(...renderEntries(plugin.entries, plan.repository, '###'));
  return `${lines.join('\n').trimEnd()}\n`;
}

function isSectionStart(line) {
  return line.startsWith('## ') && !line.startsWith('###');
}

/**
 * Replaces a section that already carries this heading instead of appending a second one, so a
 * rerun of the same cut regenerates a byte-identical file.
 */
export function upsertSection(existing, heading, section, header) {
  const text = existing ?? '';
  const lines = text === '' ? [] : text.split('\n');
  const firstSection = lines.findIndex(isSectionStart);

  const prefix = firstSection === -1 ? text : lines.slice(0, firstSection).join('\n');
  const rest = firstSection === -1 ? '' : lines.slice(firstSection).join('\n');
  const head = `${(prefix.trim() === '' ? header : prefix).trimEnd()}\n\n`;

  const restLines = rest === '' ? [] : rest.split('\n');
  const start = restLines.findIndex((line) => line.trimEnd() === heading);
  if (start !== -1) {
    let end = restLines.length;
    for (let i = start + 1; i < restLines.length; i += 1) {
      if (isSectionStart(restLines[i])) { end = i; break; }
    }
    const before = restLines.slice(0, start).join('\n');
    const after = restLines.slice(end).join('\n').trim();
    const merged = [before.trim(), section.trimEnd(), after].filter((part) => part !== '').join('\n\n');
    return `${head}${merged}\n`;
  }

  const tail = rest.trim();
  return `${head}${[section.trimEnd(), tail].filter((part) => part !== '').join('\n\n')}\n`;
}

export function releasedRefs(text) {
  const refs = new Set();
  for (const line of (text ?? '').split('\n')) {
    const match = RENDERED_ENTRY.exec(line.replace(/\r$/, ''));
    if (match) refs.add(match[1]);
  }
  return refs;
}

export function releasedFragmentFingerprints(text) {
  const fingerprints = new Set();
  const lines = (text ?? '').split('\n').map((line) => line.replace(/\r$/, ''));
  for (let index = 0; index < lines.length; index += 1) {
    const match = RENDERED_ENTRY_DETAILS.exec(lines[index]);
    if (!match) continue;

    const body = [];
    for (let bodyIndex = index + 1; bodyIndex < lines.length; bodyIndex += 1) {
      const line = lines[bodyIndex];
      if (line === '') body.push(line);
      else if (line.startsWith('  ')) body.push(line.slice(2));
      else break;
    }
    fingerprints.add(fragmentFingerprint({ title: match[1], ref: match[2], commit: match[3] ?? null, body: body.join('\n') }));
  }
  return fingerprints;
}

export function readRepoChangelog(source) {
  return source.read(REPO_CHANGELOG) ?? '';
}

export function pluginChangelogPath(plugin) {
  return path.posix.join(plugin.dir, 'CHANGELOG.md');
}

/**
 * Writes the repository changelog plus one per changed plugin and returns the repo-relative
 * paths touched, newest section first in every file.
 */
export function applyChangelogs(repoRoot, plan) {
  const written = [];

  const repoAbsolute = resolveInRepo(repoRoot, REPO_CHANGELOG);
  const repoText = existsSync(repoAbsolute) ? readFileSync(repoAbsolute, 'utf8') : '';
  writeFileSync(
    repoAbsolute,
    upsertSection(repoText, repoSectionHeading(plan), renderRepoSection(plan), repoChangelogHeader()),
  );
  written.push(REPO_CHANGELOG);

  for (const plugin of plan.plugins) {
    const relative = pluginChangelogPath(plugin);
    const absolute = resolveInRepo(repoRoot, relative, `changelog for plugin "${plugin.name}"`);
    const existing = existsSync(absolute) ? readFileSync(absolute, 'utf8') : '';
    writeFileSync(
      absolute,
      upsertSection(
        existing,
        pluginSectionHeading(plugin, plan),
        renderPluginSection(plugin, plan),
        pluginChangelogHeader(plugin.name),
      ),
    );
    written.push(relative);
  }

  return written;
}
